Testing the new module format

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,15 +1,12 @@
 #!/sbin/sh
 
-#################
-# Initialization
-#################
+TMPDIR=/dev/tmp
+MOUNTPATH=/dev/magisk_img
 
+# Default permissions
 umask 022
 
-# Global vars
-TMPDIR=/dev/tmp
-PERSISTDIR=/sbin/.magisk/mirror/persist
-
+# Initial cleanup
 rm -rf $TMPDIR 2>/dev/null
 mkdir -p $TMPDIR
 
@@ -17,25 +14,15 @@ mkdir -p $TMPDIR
 ui_print() { echo "$1"; }
 
 require_new_magisk() {
-  ui_print "*******************************"
-  ui_print " Please install Magisk v19.0+! "
-  ui_print "*******************************"
+  ui_print "***********************************"
+  ui_print " Please install the latest Magisk! "
+  ui_print "***********************************"
   exit 1
 }
 
-print_modname() {
-  local len
-  len=`echo -n $MODNAME | wc -c`
-  len=$((len + 2))
-  local pounds=`printf "%${len}s" | tr ' ' '*'`
-  ui_print "$pounds"
-  ui_print " $MODNAME "
-  ui_print "$pounds"
-  if $MAGISK; then
-    ui_print "*******************"
-    ui_print " Powered by Magisk "
-    ui_print "*******************"
-  fi
+imageless_magisk() {
+  [ $MAGISK_VER_CODE -gt 18100 ]
+  return $?
 }
 
 ##########################################################################################
@@ -49,13 +36,13 @@ mount /data 2>/dev/null
 
 # Load utility functions
 if [ -f /data/adb/magisk/util_functions.sh ]; then
-  MAGISK=true; NVBASE=/data/adb
   . /data/adb/magisk/util_functions.sh
-  [ $MAGISK_VER_CODE -gt 18100 ] || require_new_magisk
+  NVBASE=/data/adb
+elif [ -f /data/magisk/util_functions.sh ]; then
+  require_new_magisk
 else
-  [ -f /data/magisk/util_functions.sh ] && require_new_magisk
-  MAGISK=false; UF=$TMPDIR/META-INF/unity
-  unzip -oqj "$ZIPFILE" 'META-INF/unity/*' -d $TMPDIR >&2
+  UF=$TMPDIR/common/unityfiles
+  unzip -oq "$ZIPFILE" 'common/unityfiles/util_functions.sh' -d $TMPDIR >&2
   [ -f "$UF/util_functions.sh" ] || { ui_print "! Unable to extract zip file !"; exit 1; }
   . $UF/util_functions.sh
 fi
@@ -69,56 +56,107 @@ mount_partitions
 # Detect version and architecture
 api_level_arch_detect
 
-# Setup busybox and binaries, mount apex
+# Setup busybox and binaries
 $BOOTMODE && boot_actions || recovery_actions
 
 ##########################################################################################
 # Preparation
 ##########################################################################################
 
-# Extract prop file
-unzip -o "$ZIPFILE" module.prop -d $TMPDIR >&2
-[ ! -f $TMPDIR/module.prop ] && abort "! Unable to extract zip file!"
+# Extract common files
+unzip -oj "$ZIPFILE" module.prop install.sh uninstall.sh 'common/*' -d $TMPDIR >&2
 
-MODID=`grep_prop id $TMPDIR/module.prop`
-MODNAME=`grep_prop name $TMPDIR/module.prop`
+[ ! -f $TMPDIR/install.sh ] && abort "! Unable to extract zip file!"
+# Load install script
+. $TMPDIR/install.sh
+
 if $MAGISK; then
-  $BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
-  MODULEROOT=$NVBASE/$MODDIRNAME
-  MOD_VER="$NVBASE/modules/$MODID/module.prop"
-else
-  MODULEROOT=$TMPDIR
-  MOD_VER="/system/etc/$MODID-module.prop"
-fi
-MODPATH=$MODULEROOT/$MODID
-
-# Determine mod installation status - allows flash to remove in TWRP for magisk modules
-if [ -f "$MOD_VER" ]; then
-  if [ $(grep_prop versionCode $MOD_VER) -ge $(grep_prop versionCode $TMPDIR/module.prop) ]; then
-    INSTATUS=1 # Uninstall
+  if imageless_magisk; then
+    $BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
+    MODULEROOT=$NVBASE/$MODDIRNAME
   else
-    INSTATUS=2 # Upgrade
+    $BOOTMODE && IMGNAME=magisk_merge.img || IMGNAME=magisk.img
+    IMG=$NVBASE/$IMGNAME
+    request_zip_size_check "$ZIPFILE"
+    mount_magisk_img
+    MODULEROOT=$MOUNTPATH
   fi
 else
-  INSTATUS=0 # Install
+  MODULEROOT=$MOUNTPATH
 fi
 
-# Create mod paths
-rm -rf $MODPATH 2>/dev/null
-mkdir -p $MODPATH
+MODID=`grep_prop id $TMPDIR/module.prop`
+MODPATH=$MODULEROOT/$MODID
+
+print_modname
+
+# Anything after this point won't run
+
+ui_print "******************************"
+ui_print "Powered by Magisk (@topjohnwu)"
+ui_print "******************************"
 
 ##########################################################################################
 # Install
 ##########################################################################################
 
-print_modname
+# Create mod paths
+rm -rf $MODPATH 2>/dev/null
+mkdir -p $MODPATH
 
-ui_print "- Extracting module files"
-unzip -o "$ZIPFILE" -x 'META-INF/*' -d $MODPATH >&2
+on_install
 
-# Default permissions
-$MAGISK && $BOOTMODE && set_perm_recursive $MODPATH 0 0 0755 0644
+# Remove placeholder
+rm -f $MODPATH/system/placeholder 2>/dev/null
 
-# Load customization script
-[ -f $MODPATH/customize.sh ] && . $MODPATH/customize.sh
-# Nothing after this matters
+# Custom uninstaller
+[ -f $TMPDIR/uninstall.sh ] && cp -af $TMPDIR/uninstall.sh $MODPATH/uninstall.sh
+
+# Auto Mount
+if imageless_magisk; then
+  $SKIPMOUNT && touch $MODPATH/skip_mount
+else
+  $SKIPMOUNT || touch $MODPATH/auto_mount
+fi
+
+# prop files
+$PROPFILE && cp -af $TMPDIR/system.prop $MODPATH/system.prop
+
+# Module info
+cp -af $TMPDIR/module.prop $MODPATH/module.prop
+if $BOOTMODE; then
+  # Update info for Magisk Manager
+  if imageless_magisk; then
+    mktouch $NVBASE/modules/$MODID/update
+    cp -af $TMPDIR/module.prop $NVBASE/modules/$MODID/module.prop
+  else
+    mktouch /sbin/.magisk/img/$MODID/update
+    cp -af $TMPDIR/module.prop /sbin/.magisk/img/$MODID/module.prop
+  fi
+fi
+
+# post-fs-data mode scripts
+$POSTFSDATA && cp -af $TMPDIR/post-fs-data.sh $MODPATH/post-fs-data.sh
+
+# service mode scripts
+$LATESTARTSERVICE && cp -af $TMPDIR/service.sh $MODPATH/service.sh
+
+# Handle replace folders
+for TARGET in $REPLACE; do
+  mktouch $MODPATH$TARGET/.replace
+done
+
+ui_print "- Setting permissions"
+set_permissions
+
+##########################################################################################
+# Finalizing
+##########################################################################################
+
+cd /
+imageless_magisk || unmount_magisk_img
+$BOOTMODE || recovery_cleanup
+rm -rf $TMPDIR $MOUNTPATH
+
+ui_print "- Done"
+exit 0
