Rework some stuff

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -105,67 +105,6 @@ print_modname
 ui_print "- Mounting /data, /cache"
 is_mounted /data || mount /data || is_mounted /cache || mount /cache || { ui_print "! Unable to mount partitions"; exit 1; }
 
-script_type() {
-  supersuimg_mount
-  SHEBANG="#!/system/bin/sh"; ROOTTYPE="other root or rootless"; MODPATH=/system/etc/init.d; SEINJECT=/sbin/sepolicy-inject
-  if [ "$supersuimg" ] || [ -d /su ]; then
-    SHEBANG="#!/su/bin/sush"; ROOTTYPE="systemless SuperSU"; MODPATH=/su/su.d; SEINJECT=supolicy
-  elif [ -e "$(find /data /cache -name supersu_is_here | head -n1)" ]; then
-    SHEBANG="#!/su/bin/sush"; ROOTTYPE="systemless SuperSU"
-    MODPATH=$(dirname `find /data /cache -name supersu_is_here | head -n1`)/su.d
-    SEINJECT=supolicy
-  elif [ -d /system/su ] || [ -f /system/xbin/daemonsu ] || [ -f /system/xbin/sugote ]; then
-    MODPATH=/system/su.d; SEINJECT=supolicy; ROOTTYPE="system SuperSU"
-  elif [ -f /system/xbin/su ]; then
-    if [ "$(grep "SuperSU" /system/xbin/su)" ]; then
-      MODPATH=/system/su.d; ROOTTYPE="system SuperSU"; SEINJECT=supolicy
-    else
-      ROOTTYPE="LineageOS SU"
-    fi
-  fi
-}
-
-set_vars() {
-  SYS=/system
-  if [ -d /system/priv-app ]; then OLDAPP=false; else OLDAPP=true; fi
-  if $BOOTMODE; then
-    MOD_VER="/sbin/.core/img/$MODID/module.prop"
-    OLD_AML_VER="/sbin/.core/img/audmodlib/module.prop"
-  else
-    MOD_VER="$MODPATH/module.prop"
-    OLD_AML_VER="$MOUNTPATH/audmodlib/module.prop"
-  fi
-  INFO="$MODPATH/$MODID-files"
-  PROP=$MODPATH/system.prop
-  if $MAGISK && ! $SYSOVERRIDE; then
-    VEN=/system/vendor
-    UNITY="$MODPATH"
-  else
-    UNITY=""
-    if [ -d /system/addon.d ]; then
-      INFO=/system/addon.d/$MODID-files
-    else
-      INFO=/system/etc/$MODID-files
-    fi
-    if $MAGISK && $SYSOVERRIDE; then
-      patch_script $INSTALLER/common/unityfiles/modidsysover.sh
-      sed -i -e "/# CUSTOM USER SCRIPT/ r $INSTALLER/common/uninstall.sh" -e '/# CUSTOM USER SCRIPT/d' $INSTALLER/common/unityfiles/modidsysover.sh
-      cp_ch_nb $INSTALLER/common/unityfiles/modidsysover.sh $MOUNTPATH/.core/post-fs-data.d/$MODID-sysover.sh 0755 false
-    else
-      # DETERMINE SYSTEM BOOT SCRIPT TYPE
-      script_type
-      PROP=$MODPATH/$MODID-props.sh
-      MOD_VER="/system/etc/$MODID-module.prop"
-      OLD_AML_VER="/system/etc/audmodlib-module.prop"
-    fi
-  fi
-  if $DYNAMICOREO && [ $API -ge 26 ]; then
-    LIBPATCH="\/vendor"; LIBDIR=$VEN
-  else
-    LIBPATCH="\/system"; LIBDIR=/system
-  fi
-}
-
 # INSTALL
 unity_install() {
   ui_print " "
@@ -248,7 +187,13 @@ unity_install() {
   $MAGISK && [ ! -s $INFO ] && rm -f $INFO
   
   # RAMDISK PATCHES
-  $RAMDISK && ramdisk_mod 1
+  if $RAMDISK; then
+    ui_print "- Patching ramdisk"
+    cd $RD
+    . $INSTALLER/common/ramdiskinstall.sh
+    cd $DIR
+    [ "$(ls $INSTALLER/ramdisk)" ] && cp -af $INSTALLER/ramdisk/* $RD
+  fi
 
   # SET PERMISSIONS
   ui_print " "
@@ -293,7 +238,12 @@ unity_uninstall() {
   . $INSTALLER/common/uninstall.sh
   
   # RAMDISK PATCHES
-  $RAMDISK && ramdisk_mod 2
+  if $RAMDISK; then
+    ui_print "- Uninstalling ramdisk patches"
+    cd $RD
+    . $INSTALLER/common/ramdiskuninstall.sh
+    cd $DIR
+  fi
 
   ui_print " "
   ui_print "- Completing uninstall -"
@@ -367,6 +317,49 @@ done
 if $DEBUG; then
   $BOOTMODE && { ui_print " "; ui_print "  Debug info will be written to magisk log"; ui_print "  Save log in magisk manager after flashing!"; sleep 3; } || exec 3>&1 1>&2 2>&3 2>/data/media/0/$MODID-log.log
   set -x
+fi
+
+# RAMDISK
+if $RAMDISK; then
+  BOOTDIR=$INSTALLER/common/unityfiles/boot
+  AVB=$INSTALLER/common/unityfiles/avb
+  RD=$BOOTDIR/ramdisk
+  # BOOTSIGNER="/system/bin/dalvikvm -Xnodex2oat -Xnoimage-dex2oat -cp \$INSTALLER/common/unityfiles/magisk.apk com.topjohnwu.magisk.utils.BootSigner"
+  BOOTSIGNER="/system/bin/dalvikvm -Xbootclasspath:/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/bouncycastle.jar -Xnodex2oat -Xnoimage-dex2oat -cp $AVB/BootSignature_Android.jar com.android.verity.BootSignature"
+  BOOTSIGNED=false; HIGHCOMP=false; CHROMEOS=false; DIR=$(pwd)
+  mkdir -p $RD
+  cp -af $INSTALLER/common/unityfiles/$ARCH32/. $CHROMEDIR $BOOTDIR
+  chmod -R 755 $BOOTDIR
+  cp -af $BINDIR/magiskboot $RD/magiskboot
+  cd $BOOTDIR
+  find_boot_image
+  [ -z $BOOTIMAGE ] && abort "! Unable to detect target image"
+  ui_print "- Target image: $BOOTIMAGE"
+  # eval $BOOTSIGNER -verify < $BOOTIMAGE && BOOTSIGNED=true
+  eval $BOOTSIGNER -verify $BOOTIMAGE 2>&1 | grep "VALID" && BOOTSIGNED=true
+  $BOOTSIGNED && ui_print "- Boot image is signed with AVB 1.0"
+  cd $BINDIR
+  ./magiskinit -x magisk magisk
+  ui_print "- Unpacking boot image"
+  ./magiskboot --unpack "$BOOTIMAGE"
+  case $? in
+    1 ) abort "! Unable to unpack boot image";;
+    2 ) HIGHCOMP=true;;
+    3 ) ui_print "- ChromeOS boot image detected"; CHROMEOS=true;;
+    4 ) ui_print "! Sony ELF32 format detected"; abort "! Please use BootBridge from @AdrianDC to flash this mod";;
+    5 ) ui_print "! Sony ELF64 format detected" abort "! Stock kernel cannot be patched, please use a custom kernel";;
+  esac
+  ui_print "- Checking ramdisk status"
+  ./magiskboot --cpio ramdisk.cpio test
+  if [ $? -eq 2 ]; then
+    HIGHCOMP=true
+    ui_print "! Insufficient boot partition size detected"
+    ui_print "- Enabling high compression mode"
+  fi
+  cd ramdisk
+  ./magiskboot --cpio ../ramdisk.cpio "extract"
+  rm -f magiskboot
+  cd $DIR
 fi
 
 # LOAD USER VARS/FUNCTIONS
